### ISSUE TITLE
How do I use an SSL Certificate file "*.pem"

### ISSUE THREAD

**Issue by rankun203** [MisterTea/EternalTerminal#124]
With ssh I'd use 

```bash
ssh -i me.pem user@host.tld
```

wondering how I could use `me.pem` in EternalTermainal.

**Comment by ailzhang** [comment]
You could put it in ~/.ssh/config

**Comment by philCryoport** [comment]
@MisterTea Please re-open.  ~/.ssh/config file works great for ssh, but hangs for et
```
% cat ~/.ssh/config
Host foo
    Hostname ec1-2-3-4-5.us-west-1.compute.amazonaws.com
    Port 22
    User ubuntu
    IdentityFile /home/baruser/foo.pem
% ssh foo
(connects)
% et foo
(sits there with empty line)
```
Help?

**Comment by philCryoport** [comment]
Found in another ticket the command to get the debug on stdout.  Here's what I found:
```
% et -v 1 -logtostdout foo
[INFO 2019-01-31 16:57:50,052 client-main ParseConfigFile.hpp:1289] unsupported config line:     IdentityFile /home/baruser/foo.pem
          , ignored
                   [INFO 2019-01-31 16:57:50,053 client-main ParseConfigFile.hpp:1289] unsupported config line:     SendEnv LANG LC_*
             , ignored
                      [INFO 2019-01-31 16:57:50,054 client-main ParseConfigFile.hpp:1289] unsupported config line:     HashKnownHosts yes
                 , ignored
                          [INFO 2019-01-31 16:57:50,054 client-main ParseConfigFile.hpp:1289] unsupported config line:     GSSAPIAuthentication yes
                           , ignored
                                    [INFO 2019-01-31 16:57:50,055 client-main TerminalClient.cpp:280] Parsed ssh config file, connecting to ec1-2-3-4-5.us-west-1.compute.amazonaws.com
                                                                     [INFO 2019-01-31 16:57:51,019 client-main SshSetupHandler.cpp:138] etserver started
                                [INFO 2019-01-31 16:57:51,019 client-main TerminalClient.cpp:70] ID PASSKEY: <sanitized>
                                      [V1 2019-01-31 16:57:51,020 client-main ClientConnection.cpp:21] Connecting
```
...and then it just tries over and over and over again to connect

**Comment by ailzhang** [comment]
@philCryoport Which port is your etserver running on the server? Is that port open?

**Comment by philCryoport** [comment]
On the destination server "foo": 
```
$ ss -l | grep etserver
Netid                   State                     Recv-Q                    Send-Q                                                                   Local Address:Port                                                        Peer Address:Port
u_str  LISTEN   0        5                         /tmp/etserver.idpasskey.fifo 18207                                                      * 0
```
(I inserted the column headers manually.  Basically etserver is listening on port 18207)

**Comment by ailzhang** [comment]
@philCryoport  In that case you need to specify a port when connectiong `et foo:18207`. As et defaults to port 2022.

**Comment by philCryoport** [comment]
@ailzhang it's still complaining that the IdentityFile in ~/.ssh/config is unsupported by et:

```
[INFO 2019-02-01 09:45:10,822 client-main ParseConfigFile.hpp:1289] unsupported config line:     IdentityFile ~/.ssh/foo.pem
, ignored
```

Without that foo.pem file, one cannot connect using ssh to the EC2 instance to which I'm trying to connect.

Meanwhile, ssh has no complaints with the same ~/.ssh/config file

ssh does look for that filename -- and if it cannot find the file, it will error out:

```
# # # I briefly changed the IdentityFile line in ~/.ssh/config to point to a non-existent file ~/.ssh/fooa.pem
% ssh foo
no such identity: /home/baruser/.ssh/fooa.pem: No such file or directory
ubuntu@ec1-2-3-4-5.us-west-1.compute.amazonaws.com: Permission denied (publickey).
```

The problem appears to be that et does not know how to handle IdentityFile

I took a peek at https://github.com/MisterTea/EternalTerminal/blob/master/src/terminal/ParseConfigFile.hpp and it looks like the fix is probably:

1. Add support for the "IdentityFile" keyword in `enum ssh_config_opcode_e` -- (maybe `SSH_OPTIONS_IDENTITY` or `SSH_OPTIONS_ADD_IDENTITY`?)
1. Make the relevant association in `static struct ssh_config_keyword_table_s` along the lines of either: `{"identityfile", SSH_OPTIONS_IDENTITY},` or `{"identityfile", SSH_OPTIONS_ADD_IDENTITY},` (not sure which one is appropriate)
1. Add another case block in `static int ssh_config_parse_line(struct Options *options, const char *line,
unsigned int count, int *parsing, int seen[])` to cover the situation where the code encounters `SSH_OPTIONS_IDENTITY` or `SSH_OPTIONS_ADD_IDENTITY` to add `-i <identityfilename` to the ssh options (again, not sure which one is appropriate)


Temporarily, is there a way on the et command-line string to pass `-i ~/.ssh/foo.pem` ?  The documentation doesn't seem to show that.

**Comment by philCryoport** [comment]
Ping?

**Comment by MisterTea** [comment]
@philCryoport et reads your ssh config only to get the username and host alias so you don't have to "ssh me@foo.bar", you can "ssh foo".

When doing the ssh handshake, et calls ssh which will do a full read of the ssh config again and handle it correctly.  From the log you posted, the ssh part of ET is fine.  But the problem is that, after the ssh handshake, et can't connect to the et server (which runs on a different port).

You should make sure that the et port (different than the ssh port) is accessible:

```
telnet myserver 2022
```

Even without the ssh handshake, you should be able to send some data to the et server before it boots you.

**Comment by MisterTea** [comment]
@philCryoport any update?

**Comment by mathfac** [comment]
Just confirming specifying `IdentityFile` option in `~/.ssh/config` worked for me. 
```
% cat ~/.ssh/config
Host foo
    Hostname ec1-2-3-4-5.us-west-1.compute.amazonaws.com
    Port 22
    User ubuntu
    IdentityFile /home/baruser/foo.pem
```

For EC2 instances make sure that there is [the inbound security rule in AWS with opened desired port](https://intellipaat.com/community/3700/how-to-open-a-web-server-port-on-ec2-instance).
