### ISSUE TITLE
Feature request: use interactive SSH for ET login

### ISSUE THREAD

**Issue by michel-slm** [MisterTea/EternalTerminal#132]
When the ET client establishes a connection, it uses SSH in a non-interactive mode. This breaks setups that require two-factor authentication as part of an SSH connection; instead of prompting the user at the terminal the two-factor auth prompt is not displayed

```
~
$ ssh ubuntu-desktop
michel@[ubuntu-desktop-ip]'s password: 
Duo two-factor login for michel

Enter a passcode or select one of the following options:

 1. Duo Push to XXX-XXX-6598

Passcode or option (1-1): ^CConnection to [ubuntu-desktop-ip] closed.

~ 7s
❯ et ubuntu-desktop 
michel@[ubuntu-desktop-ip]'s password: 
[Duo sends code to phone]
```

**Comment by MisterTea** [comment]
I believe this is addressed, feel free to open otherwise.

**Comment by jshort** [comment]
I have this issue with a 6.1.9 client and a 6.2.1 server (MacOS).  The same situation too (login_duo).  Duo must detect that it is a non-interactive ssh session and automatically send a push notification to the first device in the list rather than splashing the prompt to choose.  @MisterTea what was the fix so I can debug to see why it isn't working for me (maybe MacOS specific).
