### ISSUE TITLE
Restoring tmux session takes too long

### ISSUE THREAD

**Issue by froody** [MisterTea/EternalTerminal#158]
Server: 5.1.8, centos-x86_64
Client: 5.1.8, MacOSX 10.14.1
See attached log file: [et-log.txt](https://github.com/MisterTea/EternalTerminal/files/2577611/et-log.txt)

Steps to reproduce
1) Launch iTerm2
2) % et centos-host:8080
3) % tmux -CC attach -d -t dev # existing session with several windows with a decent amount of history/scrollback

Even though there's a decent amount of bandwidth between these two machines, it takes over a minute for the session to transfer over. By comparison, using ssh instead of et, the session loads almost instantaneously.

**Comment by MisterTea** [comment]
Hey!  Hopefully you don't have to do this many times (the point of et is that you don't have to run et more than once).  Either way, the solution is to disable the rate-limiting (see #145 ).  But with this disabled, if you accidentally run a command that generates a ton of prints, you won't be able to easily ctrl+c to kill it.

Closing since there's a workaround, but feel free to comment if it's not complete.

**Comment by froody** [comment]
I do this a couple of times a day. I have two Macs (one desktop, one laptop) which I use to connect to a machine in a datacenter. I have an et session from each mac to the datacenter machine, but a single tmux session which I attach to, so even though I rarely run "et", I'm loading a large tmux session several times a day. I will try --noratelimit
