### ISSUE TITLE
etserver uses huge amounts of memory during port forwarding tests

### ISSUE THREAD

**Issue by MakeItGreatAgain** [MisterTea/EternalTerminal#192]
Scenario: Doing a throughput test over port forwarding. For the testbed I'm using a Raspberry Pi Model 3B running Debian buster.

Freshly started etserver uses 73,664K/4,380K (VSZ/RSS).

First I start the sender:
`cat /dev/zero | nc -k -l 2023`

Then I start the `et` client:
`et -host localhost -port 2022 -noratelimit -t 18000:2023 -x -c "sleep infinity"`

etserver memory usage: 83,908K/4,380K

Next I run the run the receiver, using pv to monitor speed and data transferred:
`nc 127.0.0.1 18000 | pv >/dev/null`

etserver memory usage: 734,152K/423,216K

The transfer speed is also highly erratic and eventually and abruptly stops completely after several hundred megabytes transferred - usually 500-600MiB.

After killing both `nc` processes and the `et` client, the `etserver` memory usage remains extremely high (as much as 70% of physical memory) until it's killed and restarted. 

There is no difference without "`-noratelimit`".

Also worth mentioning, if using an interactive program via the et connection (rather than "`sleep infinity`") it becomes unresponsive.

**Comment by MisterTea** [comment]
@MakeItGreatAgain Makes sense: I haven't stress tested ET since most people don't push the limits there, but I can explain what's going on:

The transfer speed is erratic because we have a delay to prevent spam.  The delay is supposed to allow you to ctrl-c even if you run a command that produces a bunch of spam, but I haven't finished it 100% so the delay is strictly negative.  The delay is controlled by the --no-delay parameter.  For now if you want to push a PR to turn off the delay by default, that would be appreciated.

As for the memory, there is a ring buffer for storing messages.  This way if there is a disconnect, and messages were sent but not received, those messages could be recovered.  Similarly, it is possible to evict items from the ring buffer based on how long the connection has been alive, and this would reduce the memory footprint, but no one has gotten to that yet.
