### ISSUE TITLE
et cannot find etterminal in nonstandard path

### ISSUE THREAD

**Issue by geoff-codes** [MisterTea/EternalTerminal#208]
So firstly, with the present revision/v6:
```
To run in verbose mode, pass the --v=9 flag to et.
```
...is an error. I believe the syntax is `-v 9`? 😜

Anyway Some alternative titles for this issue might be, "support running et in user mode", or, "reduce/eliminate reliance on ssh configurations". You see, I have a custom homebrew installation (not located in `/usr/local`). And while I do have `sshd` running all the time, I also try to keep my ssh config pretty restricted. So when I try `et -v 9 --logtostdout ladmin@localhost`, I get:

```
sh: line 1: etterminal: command not found
Error starting ET process through ssh, please make sure your ssh works first
```

Note that `et`, `etterminal`, and friends **in** in `ladmin`'s default path on on both the client and server (which, yes, are the same here, but that's irrelevant). It's just that the relevant component of the PATH variable is initialized in my `~/.rc` file. That is,

```
~ $ ssh ladmin@localhost 'et --help'
Password:
sh: et: command not found

~ $ ssh ladmin@localhost '. ~/.rc && et --help'
Password:
Remote shell for the busy and impatient
Usage:
  et [OPTION...] [user@]hostname[:port]

      --help                 Print help
      --version              Print version
...
```

You see what I'm saying? Its perfectly possibly to run in a nonstandard location, without root privileges, without having to edit ssh config files, etc., if you just let ssh initialize the user's shell first and collect environmental variables from there. But instead, it seems everything from the LaunchAgent to your code has hardcoded locations that are not necessarily world- or user- writable.

Is this something you'd be willing to fix?

Thank you for a lovely program!

**Comment by MisterTea** [comment]
Hey @geoff-codes!

This is why we use an interactive ssh login.  You should be able to put the path to etterminal in your .bash_profile/.zshenv so that the ssh command can find it.

Unfortunately, which startup files run when you login is quite a mess: https://medium.com/@rajsek/zsh-bash-startup-files-loading-order-bashrc-zshrc-etc-e30045652f2e

But putting the path in the appropriate startup script should solve the issue.  Feel free to reply if it doesn't and I'll reopen.
