### ISSUE TITLE
Support running without a daemon and without privileged code

### ISSUE THREAD

**Issue by dequeued0** [MisterTea/EternalTerminal#318]
It would be great if et automatically started the network server as a user from ssh (basically, like what mosh does) rather than using a daemon running as root.

**Comment by gklanderman** [comment]
would be nice if ET worked more like mosh, as then I could use/more easily adapt the mosh client/server wrappers my company has to make mosh work on their network.

on top of not requiring a root daemon

**Comment by mahnerak** [comment]
I suppose having a separate portable client (running without root access) should be even easier to accomplish, and (arguably) more valuable.

**Comment by MisterTea** [comment]
You can run et without root. Check the GitHub actions (continuous integration) to see examples.

**Comment by gklanderman** [comment]
Hi @MisterTea, can you point out the change that closes this issue?  I browsed at least a year back (further than I last installed from trunk when I was using ET at my previous employer), and didn't see any significant change to how ET works on the server side, and see that systemctl/et_service and various other system service startup files still exist.

The point of this issue was to get rid of etserver, or at least have it run as a regular user, much like mosh works, so that you do not need root on the server machine in order to be able to install/upgrade ET.

Or point to a specific GitHub action?  There are 35 pages of them...

**Comment by MisterTea** [comment]
Here's examples of etserver running as a regular user: https://github.com/MisterTea/EternalTerminal/blob/master/.circleci/config.yml

**Comment by MisterTea** [comment]
The examples use sudo but I don't think it's necessary. Please correct me if I'm wrong.
