### ISSUE TITLE
Keyboard shortcut like ctrl-c or ~. to end a "hung" session?

### ISSUE THREAD

**Issue by fryfrog** [MisterTea/EternalTerminal#484]
On ~~most~~ some of my systems running EternalTerminal server, when I reboot the connection just hangs. If I were using screen/tmux/ssh, I'd just `~.` or whatever, but I can't find anything like that for `et` and generally just have to close that terminal tab and start over.

Am I missing something obvious?

Edit: Rebooting four of them for kernel upgrades and it seems to be only one or two that hang when doing `sudo reboot && exit` instead of just ending the session. :|

**Comment by jshort** [comment]
@fryfrog so you are saying that when the server-side host is rebooted (i.e. `etterminal` and `etserver` are killed) that the client (`et`) binary just hangs? This sorts of makes sense since it's inherent with the design of eternal terminal.  The `et` client is looping and attempting to reconnect.  However, once the target server reboots and etserver comes up, it should attempt to reconnect and find that etserver is unaware of that client-id and kill the session and the client side `et` process should be killed/exit.  If this is not happening, then we have a bug to investigate.  

During the time the host is rebooting, if you want to kill those et sessions, in a separate shell/terminal, you can `pkill -x et`

**Comment by fryfrog** [comment]
I don't recall being frustrated by this for long enough that I didn't remember filing this issue. I'm just going to close it. :)
